[package]
name = "oxygraphis"
version = "0.1.6"
edition = "2021"

[workspace]

[dependencies]
anyhow = "1.0.64"
clap = { version = "4.0.8", features = ["cargo"] }
oxygraph = { path = "oxygraph" }
rayon = "1.5.3"