//! Null models for bipartite interaction matrices.
//!
//! - [`NullModel::R00`]: shuffle all cells, preserving matrix dimensions and fill only.
//! - [`NullModel::Patefield`]: random integer matrices with the observed row and column
//!   totals, drawn from the same distribution as R's `r2dtable()` (Patefield 1981).
//!   Requires integer weights. Appropriate for weighted metrics such as H2', d' and
//!   weighted modularity.
//! - [`NullModel::Curveball`]: random binary matrices with the observed row and column
//!   degrees, generated by curveball trades between pairs of rows (Strona et al. 2014).
//!   Appropriate for binary metrics such as NODF.
//!
//! Every null matrix is generated independently from the observed matrix, so curveball
//! nulls do not depend on one another (unlike a single sequential chain).

use ndarray::Array2;
use rand::seq::SliceRandom;
use rand::Rng;
use std::fmt;
use std::str::FromStr;
use thiserror::Error;

/// Errors from null model generation.
#[derive(Error, Debug)]
pub enum NullModelError {
    #[error("The Patefield null model requires non-negative integer weights.")]
    NonInteger,
    #[error("Unknown null model '{0}'. Choose r00, patefield or curveball.")]
    Unknown(String),
}

/// The available null models.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NullModel {
    R00,
    Patefield,
    Curveball,
}

impl FromStr for NullModel {
    type Err = NullModelError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "r00" => Ok(NullModel::R00),
            "patefield" | "r2dtable" => Ok(NullModel::Patefield),
            "curveball" => Ok(NullModel::Curveball),
            other => Err(NullModelError::Unknown(other.to_string())),
        }
    }
}

impl fmt::Display for NullModel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            NullModel::R00 => "r00",
            NullModel::Patefield => "patefield",
            NullModel::Curveball => "curveball",
        };
        write!(f, "{}", s)
    }
}

/// Default number of curveball trades per null matrix: enough for every row to take part
/// in many trades, with a floor for very small matrices.
pub fn default_trades(nrows: usize) -> usize {
    (50 * nrows).max(1000)
}

/// Shuffle all cells of the matrix (r00 for binary data; for weighted data the weights are
/// shuffled with the zeros).
pub fn r00<R: Rng + ?Sized>(matrix: &Array2<f64>, rng: &mut R) -> Array2<f64> {
    let mut values: Vec<f64> = matrix.iter().copied().collect();
    values.shuffle(rng);
    Array2::from_shape_vec(matrix.raw_dim(), values).expect("same shape")
}

/// Log-factorial table for 0..=n.
fn log_factorials(n: usize) -> Vec<f64> {
    let mut lf = vec![0.0; n + 1];
    for i in 1..=n {
        lf[i] = lf[i - 1] + (i as f64).ln();
    }
    lf
}

/// Draw from a hypergeometric distribution: `draws` items taken without replacement from a
/// population of `pop` containing `succ` successes. Inverse-CDF sampling from the lower bound.
fn hypergeometric<R: Rng + ?Sized>(pop: usize, succ: usize, draws: usize, lf: &[f64], rng: &mut R) -> usize {
    let lo = draws.saturating_sub(pop - succ);
    let hi = draws.min(succ);
    if lo == hi {
        return lo;
    }
    let ln_choose = |n: usize, k: usize| lf[n] - lf[k] - lf[n - k];
    let ln_denom = ln_choose(pop, draws);
    let u: f64 = rng.gen_range(0.0..1.0);
    let mut cum = 0.0;
    for x in lo..=hi {
        cum += (ln_choose(succ, x) + ln_choose(pop - succ, draws - x) - ln_denom).exp();
        if u < cum {
            return x;
        }
    }
    hi
}

/// Random integer matrix with the same row and column totals as `matrix`, sampled from the
/// distribution used by R's `r2dtable()` (Patefield 1981). Each row is drawn from a
/// multivariate hypergeometric distribution given the remaining column totals.
pub fn patefield<R: Rng + ?Sized>(matrix: &Array2<f64>, rng: &mut R) -> Result<Array2<f64>, NullModelError> {
    if matrix.iter().any(|&v| v < 0.0 || v.fract() != 0.0) {
        return Err(NullModelError::NonInteger);
    }
    let (nr, nc) = matrix.dim();
    let row_tot: Vec<usize> = matrix.rows().into_iter().map(|r| r.sum() as usize).collect();
    let mut col_rem: Vec<usize> = matrix.columns().into_iter().map(|c| c.sum() as usize).collect();
    let total: usize = row_tot.iter().sum();
    let lf = log_factorials(total);
    let mut out = Array2::<f64>::zeros((nr, nc));

    for i in 0..nr {
        let mut row_rem = row_tot[i];
        // population still to be allocated across columns j.. for this and later rows
        let mut pop: usize = col_rem.iter().sum();
        for j in 0..nc {
            let x = if j == nc - 1 {
                row_rem
            } else {
                hypergeometric(pop, col_rem[j], row_rem, &lf, rng)
            };
            out[[i, j]] = x as f64;
            pop -= col_rem[j];
            row_rem -= x;
            col_rem[j] -= x;
        }
    }
    Ok(out)
}

/// Random binary matrix with the same row and column degrees as the binarised `matrix`,
/// produced by `trades` curveball trades (Strona et al. 2014).
pub fn curveball<R: Rng + ?Sized>(matrix: &Array2<f64>, trades: usize, rng: &mut R) -> Array2<f64> {
    let (nr, nc) = matrix.dim();
    let mut rows: Vec<Vec<usize>> = matrix
        .rows()
        .into_iter()
        .map(|r| r.iter().enumerate().filter(|(_, &v)| v > 0.0).map(|(j, _)| j).collect())
        .collect();

    if nr >= 2 {
        // mark[j]: bit 1 = column j in row a, bit 2 = column j in row b
        let mut mark = vec![0u8; nc];
        for _ in 0..trades {
            let a = rng.gen_range(0..nr);
            let mut b = rng.gen_range(0..nr - 1);
            if b >= a {
                b += 1;
            }
            for &j in &rows[a] {
                mark[j] |= 1;
            }
            for &j in &rows[b] {
                mark[j] |= 2;
            }
            let mut shared = Vec::new();
            let mut pool = Vec::new();
            for &j in &rows[a] {
                if mark[j] == 3 {
                    shared.push(j);
                } else {
                    pool.push(j);
                }
            }
            let n_a = pool.len();
            for &j in &rows[b] {
                if mark[j] == 2 {
                    pool.push(j);
                }
            }
            for &j in rows[a].iter().chain(rows[b].iter()) {
                mark[j] = 0;
            }
            if n_a == 0 || pool.len() == n_a {
                continue;
            }
            pool.shuffle(rng);
            let mut new_a = shared.clone();
            new_a.extend_from_slice(&pool[..n_a]);
            let mut new_b = shared;
            new_b.extend_from_slice(&pool[n_a..]);
            rows[a] = new_a;
            rows[b] = new_b;
        }
    }

    let mut out = Array2::<f64>::zeros((nr, nc));
    for (i, r) in rows.iter().enumerate() {
        for &j in r {
            out[[i, j]] = 1.0;
        }
    }
    out
}

/// Generate one null matrix from `matrix` under `model`.
pub fn null_matrix<R: Rng + ?Sized>(
    matrix: &Array2<f64>,
    model: NullModel,
    trades: usize,
    rng: &mut R,
) -> Result<Array2<f64>, NullModelError> {
    match model {
        NullModel::R00 => Ok(r00(matrix, rng)),
        NullModel::Patefield => patefield(matrix, rng),
        NullModel::Curveball => Ok(curveball(matrix, trades, rng)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ndarray::{array, Axis};
    use rand::rngs::StdRng;
    use rand::SeedableRng;

    fn web() -> Array2<f64> {
        array![
            [5.0, 0.0, 2.0, 1.0, 0.0],
            [0.0, 3.0, 0.0, 4.0, 1.0],
            [2.0, 1.0, 0.0, 0.0, 6.0],
            [0.0, 0.0, 3.0, 2.0, 0.0]
        ]
    }

    #[test]
    fn patefield_preserves_totals() {
        let m = web();
        let mut rng = StdRng::seed_from_u64(1);
        for _ in 0..200 {
            let n = patefield(&m, &mut rng).unwrap();
            assert_eq!(n.sum_axis(Axis(1)), m.sum_axis(Axis(1)));
            assert_eq!(n.sum_axis(Axis(0)), m.sum_axis(Axis(0)));
            assert!(n.iter().all(|&v| v >= 0.0 && v.fract() == 0.0));
        }
    }

    #[test]
    fn patefield_matches_independence_expectation() {
        // E[n_ij] = r_i c_j / N under the Patefield distribution.
        let m = web();
        let (rs, cs, tot) = (m.sum_axis(Axis(1)), m.sum_axis(Axis(0)), m.sum());
        let mut rng = StdRng::seed_from_u64(2);
        let reps = 20000;
        let mut acc = Array2::<f64>::zeros(m.raw_dim());
        for _ in 0..reps {
            acc = acc + patefield(&m, &mut rng).unwrap();
        }
        let mean = acc / reps as f64;
        for ((i, j), &v) in mean.indexed_iter() {
            let e = rs[i] * cs[j] / tot;
            assert!((v - e).abs() < 0.05, "cell ({i},{j}): {v} vs {e}");
        }
    }

    #[test]
    fn patefield_rejects_non_integer() {
        let m = array![[1.5, 0.0], [0.0, 1.0]];
        assert!(patefield(&m, &mut StdRng::seed_from_u64(3)).is_err());
    }

    #[test]
    fn curveball_preserves_degrees_and_mixes() {
        let m = web().mapv(|v| if v > 0.0 { 1.0 } else { 0.0 });
        let mut rng = StdRng::seed_from_u64(4);
        let mut changed = 0;
        for _ in 0..200 {
            let n = curveball(&m, default_trades(m.nrows()), &mut rng);
            assert_eq!(n.sum_axis(Axis(1)), m.sum_axis(Axis(1)));
            assert_eq!(n.sum_axis(Axis(0)), m.sum_axis(Axis(0)));
            if n != m {
                changed += 1;
            }
        }
        assert!(changed > 100);
    }

    #[test]
    fn parse_null_model() {
        assert_eq!("Patefield".parse::<NullModel>().unwrap(), NullModel::Patefield);
        assert_eq!("curveball".parse::<NullModel>().unwrap(), NullModel::Curveball);
        assert!("swap".parse::<NullModel>().is_err());
    }
}
