[package]
name = "oxygraph"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
petgraph = "0.6.2"
thiserror = "1.0.32"
serde = "1.0.143"
serde_derive = "1.0.143"
permutation = "0.4.1"
itertools = "0.10.3"
